# This is a basic workflow to help you get started with Actions

  
name: Setup ROS environment
  uses: ros-tooling/setup-ros@0.0.14
  with:
    # List of binary ROS distributions to be installed.

Support for non-Linux platform is not implemented yet, so this
parameter is ignored on Mac OS X and Windows.

Allowed ROS distributions
- "" (no value) - no ROS binary installation
- kinetic
- melodic
- dashing
- eloquent
- source

Multiple values can be passed using a whitespace delimited list
"melodic dashing".

For each passed ROS distribution, its desktop variant will be installed.

    required-ros-distributions: # optional, default is 
